### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by dreinon** [LouisTsiattalou/tfidf_matcher#2]
Hi!
Is this project currently active? I see tests are failing but I have seen it recommended in [this stackoverflow post](https://stackoverflow.com/questions/64775714/fuzzy-matching-not-accurate-enough-with-tf-idf-and-cosine-similarity), so I would like to give it a try!

Thanks!

**Comment by LouisTsiattalou** [comment]
Hiya, the project should be in a working state, the tests are probably failing because I'm not using Travis CI anymore. Feel free to give it a go and let me know if you have any questions. I also review PRs if you have any contributions. Cheers!

**Comment by kraftaa** [comment]
@LouisTsiattalou so far it worked very well for me, thank you! 100K vs 8mln fuzzy search less than in 4h it's very impressive, all other python libraries were going into 'infinite sleep', postgres similarity was taking forever - and I had to clean all upper/lower/commas/braces etc from both datasets , rust wasn't much help either. I'm still going through the results, but so far it's very good.

update: I found that if original text has many whitespaces together like '            ', and the look up text has many whitespaces together - they matched as 0.96, even if the rest are not even close.

**Comment by LouisTsiattalou** [comment]
Thanks for your feedback, glad you're finding it useful! There's a new version available today, but it doesn't have any improvements to the methodology, just some housekeeping thanks to efforts of @EnderWolf50 (https://github.com/LouisTsiattalou/tfidf_matcher/pull/3).
